<?php

namespace AppBundle\Repository;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProductsInCart(int $id){
        return $this->createQueryBuilder("c")
            ->innerJoin("c.products", "p")
            ->innerJoin("c.", "dc")
            ->where("dc.id=:pcId")
            ->setParameter("pcId", $id)
            ->getQuery()
            ->getResult();
    }
}
