<?php

namespace AppBundle\Repository;

/**
 * OrderedProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderedProductRepository extends \Doctrine\ORM\EntityRepository
{
}
