<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllProducts()
    {
        return $this->createQueryBuilder("p")
            ->where("p.quantity > :minQuantity")
            ->orderBy("p.id", "DESC")
            ->setParameter("minQuantity", 0)
            ->getQuery()
            ->getResult();

    }

    public function getLastThreeProducts()
    {
        return $this->createQueryBuilder("p")
            ->where("p.quantity > :minQuantity")
            ->orderBy("p.id", "DESC")
            ->setMaxResults(3)
            ->setParameter("minQuantity", 0)
            ->getQuery()
            ->getResult();

    }
}
