<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllProducts()
    {
        return $this->createQueryBuilder("p")
            ->where("p.quantity > :minQuantity")
            ->orderBy("p.id", "DESC")
            ->setParameter("minQuantity", 0)
            ->getQuery()
            ->getResult();

    }

    public function getLastThreeProducts()
    {
        return $this->createQueryBuilder("p")
            ->where("p.quantity > :minQuantity")
            ->orderBy("p.id", "DESC")
            ->setMaxResults(3)
            ->setParameter("minQuantity", 0)
            ->getQuery()
            ->getResult();

    }

    public function getAllProductsFromCategory($id)
    {
        return $this->createQueryBuilder("p")
            ->join("p.category", 'c')
            ->where("p.quantity > :minQuantity")
            ->where('c.id=:catId')
            ->orderBy("p.id", "DESC")
            ->setParameter("catId", $id)
            ->getQuery()
            ->getResult();

    }

    public function getPromoThreeProducts()
    {
        return $this->createQueryBuilder("p")
            ->where("p.promoPrice IS NOT NULL")
            ->orderBy("p.id", "DESC")
            ->setMaxResults(3)
            ->getQuery()
            ->getResult();

    }

    public function getPromoAllProducts()
    {
        return $this->createQueryBuilder("p")
            ->where("p.promoPrice IS NOT NULL")
            ->orderBy("p.id", "DESC")
            ->getQuery()
            ->getResult();

    }
}
